### ISSUE TITLE
버그 문의드립니다.

### ISSUE THREAD

**Issue by Ezmuraerror** [Riey/EmueraFramework#3]
eraIm@sPOFA 0.06I 및 eraIm@sPOFA 0.07을 실행하면 다음과 같은 버그가 나면서 진행이 안됩니다.  프레임워크 버전은 1.3.4입니다. 

Now Loading...
警告Lv2:_VARIABLE.ERH:110行目:キャラ型変数にSAVEDATAフラグを付ける場合には「バイナリ型セーブ」オプションが必須です
ERHの読み込み中にエラーが発生したため処理を終了しました

<구글번역>
경고 Lv2 : _VARIABLE.ERH : 110 라인 : 캐릭터 형 변수에 SAVEDATA 플래그를 붙이는 경우에는 "이진 저장"옵션이 필요합니다
ERH로드하는 동안 오류가 발생하여 작업을 완료했습니다

**Comment by Riey** [comment]
https://github.com/Riey/EmueraFramework/releases/tag/1.3.4

1.3.4를 쓰시면 됩니다
